Add CLDR pluralisation in linting rules
ZimbraOS/eslint-plugin-preact-i18n pull request #6
Opened 2021-05-11 14:45 UTC by msfstef

2021-05-11 15:08 UTC, billneff79 commented on test/i18n/en.json
> +  "pluralizedZeroOneOther": {
I think you meant `badPluralizedZeroOneOther`, and you might want to have the subkey be `zero` instead of `one` to differentiate from none-one-many

2021-05-11 15:13 UTC, billneff79 commented on test/i18n/en.json
> +  "pluralizedZeroOneOther": {
this should basically match what you have in the .md file

2021-05-11 15:15 UTC, billneff79 commented on test/src/rules/no-unknown-key.spec.js
> +					message: "[zero,other] pluralization keys are missing for key 'badPluralizedNoneOneMany' in 'en' language",
This is not the expected error message.  Please update to be accurate

2021-05-11 15:28 UTC, billneff79 requested changes
Thanks for the contribution.  Couple changes and this should be all sset

2021-05-11 15:34 UTC, msfstef commented on test/src/rules/no-unknown-key.spec.js
> +					message: "[zero,other] pluralization keys are missing for key 'badPluralizedNoneOneMany' in 'en' language",
changed the example to use only the "one" form so that everything matches the one in the md

2021-05-11 17:13 UTC, billneff79 approved these changes
Looks good.  I'll get this merged and deployed.

2021-05-11 17:58 UTC, billneff79 commented on test/i18n/en.json
> +    "zero": "No Things",
you've got a trailing comma here that is breaking the unit tests

2021-05-11 18:00 UTC, billneff79 commented on test/src/rules/no-unknown-key.spec.js
> +		{ code: '<Text id="pluralizedZeroOneOther" plural="0" />' },
These unit tests are failing right now.  The rule logic is not sophisticated enough right now to see  `one` defined and check both `none-one-many` and `zero-one-other` - it is just hitting none-one-many first and saying it fails.  You'll need to update the no-unknown-key.js file logic to account for this overlap

2021-05-11 18:01 UTC, billneff79 requested changes
more changes needed to get unit tests to pass

2021-05-17 18:45 UTC, msfstef commented
Changed some of the logic and fixed the issues - tests passing now

2021-05-26 13:22 UTC, msfstef commented
Are there any other changes needed to merge this?

2021-05-28 19:41 UTC, billneff79 commented on src/rules/no-unknown-key.js
> +			const matchingKeyForms = PLURAL_KEY_FORMS.filter(keyForms => {
Instead of a `filter` and an `if (matchingKeyForms.length >0)` later, just combine this into a single
```js

if ( PLURAL_KEY_FORMS.some(keyForms => keyForms.every(plural => has(translation, `${key}.${plural}`))) {
    // If there is a form where every required pluralization key is present, it is all set
    return;
}
```

2021-05-28 19:42 UTC, billneff79 commented on src/rules/no-unknown-key.js
> +				if (matchingKeys.length === keyForms.length) return false;
This line is unnecessary - because of the earlier check for a good match, this would never occur

2021-05-28 20:03 UTC, billneff79 approved these changes
I simplified the logic to only loop over the keyForms one time

2021-05-28 20:04 UTC, merged